extends Node

const weapons_level_color = {
	1.0 : Color(0,0,0,1),
	2.0 : Color(10,0,0,1),
	3.0 : Color(0,10,0,1),
	4.0 : Color(0,0,10,1),
}

func _ready():
	pass
	# for i in weapons_data:
	# 	var weapon_data = weapons_data[i]
	# 	var mult = max(1,weapon_data["K_TP"]*2)*max(1,weapon_data["K_RICO"]*2)*max(1,weapon_data["K_SPL"]*2)
	# 	var price = (weapon_data["K_ATK"]*15+(weapon_data["K_ATK_RNG"]-150)*2 \
	#  	+weapon_data["K_EXPL_RNG"]*50+weapon_data["K_EXPL_DMG"]*50+weapon_data["K_ACCURACY"]*50\
	#  	+weapon_data["K_CRIT_RATE"]*50+weapon_data["K_GROWTH"]*10)*mult
	# 	var final_price = float(price)/float(weapon_data["K_ATK_INTVL"])
	# 	print(final_price)
	# 	weapons_data[i].merge({"K_PRICE":final_price},true)
	# print(weapons_data)
	# for i in weapons_data:
	# 	print("[\""+i+"\","+str(weapons_data[i]["K_PRICE"])+"]")

#base price 100,base dmg = 15/pt
#accuracy as 0,crit rate as 0,worth 50/pt,
#exp = 0,worth 50/pt,atk range 150base,2/pt,
#special atk as 0,worth 300/pt,growth base 0,10/pts
const weapons_data = {
	"WEAPON1":{
		"K_IMG": "res://asset/weapon/1.png",
		"bullet_img": "res://asset/weapon/bullet/1.png",
		"explosion_img": "res://asset/weapon/explosion/1.png",
		"audio": "res://asset/weapon/sound/1.wav",
		"K_ATK": 40,
		"K_ATK_RNG": 200,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 1,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 50,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 6600
	},
	"WEAPON2":{
		"K_IMG": "res://asset/weapon/2.png",
		"bullet_img": "res://asset/weapon/bullet/2.png",
		"explosion_img": "res://asset/weapon/explosion/2.png",
		"audio": "res://asset/weapon/sound/2.wav",
		"K_ATK": 12,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 3,
		"K_EXPL_RNG": 100,
		"K_EXPL_DMG": 30,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 2260
	},
	"WEAPON3":{
		"K_IMG": "res://asset/weapon/3.png",
		"bullet_img": "res://asset/weapon/bullet/3.png",
		"explosion_img": "res://asset/weapon/explosion/3.png",
		"audio": "res://asset/weapon/sound/3.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 0.5,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 2,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 2000
	},
	"WEAPON4":{
		"K_IMG": "res://asset/weapon/4.png",
		"bullet_img": "res://asset/weapon/bullet/4.png",
		"explosion_img": "res://asset/weapon/explosion/4.png",
		"audio": "res://asset/weapon/sound/4.wav",
		"K_ATK": 30,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1.5,
		"K_EXPL_RNG": 50,
		"K_EXPL_DMG": 50,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": -20,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 3033.33333333333
	},
	"WEAPON5":{
		"K_IMG": "res://asset/weapon/5.png",
		"bullet_img": "res://asset/weapon/bullet/5.png",
		"explosion_img": "res://asset/weapon/explosion/5.png",
		"audio": "res://asset/weapon/sound/5.wav",
		"K_ATK": 16,
		"K_ATK_RNG": 100,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 30,
		"K_GROWTH": 10,
		"K_PRICE": 1740
	},
	"WEAPON6":{
		"K_IMG": "res://asset/weapon/6.png",
		"bullet_img": "res://asset/weapon/bullet/6.png",
		"explosion_img": "res://asset/weapon/explosion/6.png",
		"audio": "res://asset/weapon/sound/6.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 350,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 2,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 10,
		"K_GROWTH": 10,
		"K_PRICE": 4600
	},
	"WEAPON7":{
		"K_IMG": "res://asset/weapon/7.png",
		"bullet_img": "res://asset/weapon/bullet/7.png",
		"explosion_img": "res://asset/weapon/explosion/7.png",
		"audio": "res://asset/weapon/sound/7.wav",
		"K_ATK": 15,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 4,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 3,
		"K_ACCURACY": 20,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 1987.5
	},
	"WEAPON8":{
		"K_IMG": "res://asset/weapon/8.png",
		"bullet_img": "res://asset/weapon/bullet/8.png",
		"explosion_img": "res://asset/weapon/explosion/8.png",
		"audio": "res://asset/weapon/sound/8.wav",
		"K_ATK": 100,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 2.5,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 3,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 40,
		"K_GROWTH": 10,
		"K_PRICE": 8640
	},
	"WEAPON9":{
		"K_IMG": "res://asset/weapon/9.png",
		"bullet_img": "res://asset/weapon/bullet/9.png",
		"explosion_img": "res://asset/weapon/explosion/9.png",
		"audio": "res://asset/weapon/sound/9.wav",
		"K_ATK": 30,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 275
	},
	"WEAPON10":{
		"K_IMG": "res://asset/weapon/10.png",
		"bullet_img": "res://asset/weapon/bullet/10.png",
		"explosion_img": "res://asset/weapon/explosion/10.png",
		"audio": "res://asset/weapon/sound/10.wav",
		"K_ATK": 40,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 4,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 4,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": -10,
		"K_CRIT_RATE": 30,
		"K_GROWTH": 10,
		"K_PRICE": 3400
	},
	"WEAPON11":{
		"K_IMG": "res://asset/weapon/11.png",
		"bullet_img": "res://asset/weapon/bullet/11.png",
		"explosion_img": "res://asset/weapon/explosion/11.png",
		"audio": "res://asset/weapon/sound/11.wav",
		"K_ATK": 45,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 2,
		"K_SPL": 2,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 6200
	},
	"WEAPON12":{
		"K_IMG": "res://asset/weapon/12.png",
		"bullet_img": "res://asset/weapon/bullet/12.png",
		"explosion_img": "res://asset/weapon/explosion/12.png",
		"audio": "res://asset/weapon/sound/12.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 125
	},
	"WEAPON13":{
		"K_IMG": "res://asset/weapon/13.png",
		"bullet_img": "res://asset/weapon/bullet/13.png",
		"explosion_img": "res://asset/weapon/explosion/13.png",
		"audio": "res://asset/weapon/sound/13.wav",
		"K_ATK": 100,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 10,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 10,
		"K_GROWTH": 30,
		"K_PRICE": 230
	},
	"WEAPON14":{
		"K_IMG": "res://asset/weapon/14.png",
		"bullet_img": "res://asset/weapon/bullet/14.png",
		"explosion_img": "res://asset/weapon/explosion/14.png",
		"audio": "res://asset/weapon/sound/14.wav",
		"K_ATK": 20,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 100,
		"K_EXPL_DMG": 10,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 5900
	},
	"WEAPON15":{
		"K_IMG": "res://asset/weapon/15.png",
		"bullet_img": "res://asset/weapon/bullet/15.png",
		"explosion_img": "res://asset/weapon/explosion/15.png",
		"audio": "res://asset/weapon/sound/15.wav",
		"K_ATK": 20,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 20,
		"K_CRIT_RATE": 20,
		"K_GROWTH": 15,
		"K_PRICE": 2450
	},
	"WEAPON16":{
		"K_IMG": "res://asset/weapon/16.png",
		"bullet_img": "res://asset/weapon/bullet/16.png",
		"explosion_img": "res://asset/weapon/explosion/16.png",
		"audio": "res://asset/weapon/sound/16.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 250,
		"K_ATK_INTVL": 2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 80,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 20,
		"K_PRICE": 2275
	},
	"WEAPON17":{
		"K_IMG": "res://asset/weapon/17.png",
		"bullet_img": "res://asset/weapon/bullet/17.png",
		"explosion_img": "res://asset/weapon/explosion/17.png",
		"audio": "res://asset/weapon/sound/17.wav",
		"K_ATK": 35,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1.8,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 2,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 1388.88888888889
	},
	"WEAPON18":{
		"K_IMG": "res://asset/weapon/18.png",
		"bullet_img": "res://asset/weapon/bullet/18.png",
		"explosion_img": "res://asset/weapon/explosion/18.png",
		"audio": "res://asset/weapon/sound/18.wav",
		"K_ATK": 200,
		"K_ATK_RNG": 130,
		"K_ATK_INTVL": 1.8,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 1700
	},
	"WEAPON19":{
		"K_IMG": "res://asset/weapon/19.png",
		"bullet_img": "res://asset/weapon/bullet/19.png",
		"explosion_img": "res://asset/weapon/explosion/19.png",
		"audio": "res://asset/weapon/sound/19.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 100,
		"K_EXPL_DMG": 50,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 7750
	},
	"WEAPON20":{
		"K_IMG": "res://asset/weapon/20.png",
		"bullet_img": "res://asset/weapon/bullet/20.png",
		"explosion_img": "res://asset/weapon/explosion/20.png",
		"audio": "res://asset/weapon/sound/20.wav",
		"K_ATK": 15,
		"K_ATK_RNG": 100,
		"K_ATK_INTVL": 0.2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 1125
	},
	"WEAPON21":{
		"K_IMG": "res://asset/weapon/21.png",
		"bullet_img": "res://asset/weapon/bullet/21.png",
		"explosion_img": "res://asset/weapon/explosion/21.png",
		"audio": "res://asset/weapon/sound/21.wav",
		"K_ATK": 25,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 1,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 950
	},
	"WEAPON22":{
		"K_IMG": "res://asset/weapon/22.png",
		"bullet_img": "res://asset/weapon/bullet/22.png",
		"explosion_img": "res://asset/weapon/explosion/22.png",
		"audio": "res://asset/weapon/sound/22.wav",
		"K_ATK": 15,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1.6,
		"K_EXPL_RNG": 150,
		"K_EXPL_DMG": 36,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 6015.625
	},
	"WEAPON23":{
		"K_IMG": "res://asset/weapon/23.png",
		"bullet_img": "res://asset/weapon/bullet/23.png",
		"explosion_img": "res://asset/weapon/explosion/23.png",
		"audio": "res://asset/weapon/sound/23.wav",
		"K_ATK": 30,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 3,
		"K_EXPL_RNG": 100,
		"K_EXPL_DMG": 80,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 3183.33333333333
	},
	"WEAPON24":{
		"K_IMG": "res://asset/weapon/24.png",
		"bullet_img": "res://asset/weapon/bullet/24.png",
		"explosion_img": "res://asset/weapon/explosion/24.png",
		"audio": "res://asset/weapon/sound/24.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 0.4,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 625
	},
	"WEAPON25":{
		"K_IMG": "res://asset/weapon/25.png",
		"bullet_img": "res://asset/weapon/bullet/25.png",
		"explosion_img": "res://asset/weapon/explosion/25.png",
		"audio": "res://asset/weapon/sound/25.wav",
		"K_ATK": 30,
		"K_ATK_RNG": 180,
		"K_ATK_INTVL": 2.5,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 60,
		"K_GROWTH": 10,
		"K_PRICE": 1444
	},
	"WEAPON26":{
		"K_IMG": "res://asset/weapon/26.png",
		"bullet_img": "res://asset/weapon/bullet/26.png",
		"explosion_img": "res://asset/weapon/explosion/26.png",
		"audio": "res://asset/weapon/sound/26.wav",
		"K_ATK": 20,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 1,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 800
	},
	"WEAPON27":{
		"K_IMG": "res://asset/weapon/27.png",
		"bullet_img": "res://asset/weapon/bullet/27.png",
		"explosion_img": "res://asset/weapon/explosion/27.png",
		"audio": "res://asset/weapon/sound/27.wav",
		"K_ATK": 20,
		"K_ATK_RNG": 130,
		"K_ATK_INTVL": 2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 2,
		"K_SPL": 0,
		"K_ACCURACY": -30,
		"K_CRIT_RATE": 30,
		"K_GROWTH": 10,
		"K_PRICE": 720
	},
	"WEAPON28":{
		"K_IMG": "res://asset/weapon/28.png",
		"bullet_img": "res://asset/weapon/bullet/28.png",
		"explosion_img": "res://asset/weapon/explosion/28.png",
		"audio": "res://asset/weapon/sound/28.wav",
		"K_ATK": 120,
		"K_ATK_RNG": 170,
		"K_ATK_INTVL": 3,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 2,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 20,
		"K_GROWTH": 10,
		"K_PRICE": 3920
	},
	"WEAPON29":{
		"K_IMG": "res://asset/weapon/29.png",
		"bullet_img": "res://asset/weapon/bullet/29.png",
		"explosion_img": "res://asset/weapon/explosion/29.png",
		"audio": "res://asset/weapon/sound/5.wav",
		"K_ATK": 65,
		"K_ATK_RNG": 200,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 10,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 15,
		"K_GROWTH": 10,
		"K_PRICE": 1925
	},
	"WEAPON30":{
		"K_IMG": "res://asset/weapon/30.png",
		"bullet_img": "res://asset/weapon/bullet/30.png",
		"explosion_img": "res://asset/weapon/explosion/30.png",
		"audio": "res://asset/weapon/sound/4.wav",
		"K_ATK": 20,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 2,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 200
	},
	"WEAPON31":{
		"K_IMG": "res://asset/weapon/31.png",
		"bullet_img": "res://asset/weapon/bullet/31.png",
		"explosion_img": "res://asset/weapon/explosion/31.png",
		"audio": "res://asset/weapon/sound/3.wav",
		"K_ATK": 5,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 0.5,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 350
	},
	"WEAPON32":{
		"K_IMG": "res://asset/weapon/32.png",
		"bullet_img": "res://asset/weapon/bullet/32.png",
		"explosion_img": "res://asset/weapon/explosion/32.png",
		"audio": "res://asset/weapon/sound/2.wav",
		"K_ATK": 25,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 50,
		"K_EXPL_DMG": 50,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 10,
		"K_PRICE": 5475
	},
	"WEAPON33":{
		"K_IMG": "res://asset/weapon/33.png",
		"bullet_img": "res://asset/weapon/bullet/33.png",
		"explosion_img": "res://asset/weapon/explosion/33.png",
		"audio": "res://asset/weapon/sound/1.wav",
		"K_ATK": 10,
		"K_ATK_RNG": 150,
		"K_ATK_INTVL": 1,
		"K_EXPL_RNG": 0,
		"K_EXPL_DMG": 0,
		"K_TP": 0,
		"K_RICO": 0,
		"K_SPL": 0,
		"K_ACCURACY": 0,
		"K_CRIT_RATE": 0,
		"K_GROWTH": 0,
		"K_PRICE": 150
	}}
